### ISSUE TITLE
Task :spotlessJava FAILED when minimizing many different methods

### ISSUE THREAD

**Issue by jonathan-m-phillips** [kelloggm/specimin#110]
I was running ASHE's RepositoryAutomationEngine, which minimizes many different methods within a set of given repositories. For many methods (it is very unlikely to check all in a dryrun when we let it run for 10+ minutes), we were experiencing the following error from Specimin:
14:14:47.642 [main] INFO  edu.njit.jerse.automation.AsheAutomation - Fully qualified method reference: org.checkerframework.dataflow.cfg.node.VariableDeclarationNode#equals(Object)

Task :spotlessJava FAILED
Step 'google-java-format' found problem in 'src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java':
'com.sun.tools.javac.tree.JCTree com.sun.tools.javac.tree.JCTree$JCImport.getQualifiedIdentifier()'
java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.JCTree com.sun.tools.javac.tree.JCTree$JCImport.getQualifiedIdentifier()'
	at com.google.googlejavaformat.java.RemoveUnusedImports.getSimpleName(RemoveUnusedImports.java:296)
	at com.google.googlejavaformat.java.RemoveUnusedImports.buildReplacements(RemoveUnusedImports.java:278)
 	at com.google.googlejavaformat.java.RemoveUnusedImports.removeUnusedImports(RemoveUnusedImports.java:227)
 	at com.diffplug.spotless.glue.java.GoogleJavaFormatFormatterFunc.apply(GoogleJavaFormatFormatterFunc.java:58)
 	at com.diffplug.spotless.FormatterFunc.apply(FormatterFunc.java:32)
 	at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:82)
 	at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:88)
 	at com.diffplug.spotless.Formatter.compute(Formatter.java:246)
 	at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:203)
 	at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:190)
 	at com.diffplug.gradle.spotless.SpotlessTaskImpl.processInputFile(SpotlessTaskImpl.java:105)
 	at com.diffplug.gradle.spotless.SpotlessTaskImpl.performAction(SpotlessTaskImpl.java:89)

It appears during minimization, Specimin is expecting the proper Spotless formatting. Note that I was using the most current main branch.

If you experience the same issue when minimizing the given example, please mention below! Again, I was experiencing this on multiple different methods.

**Comment by kelloggm** [comment]
> It appears during minimization, Specimin is expecting the proper Spotless formatting. Note that I was using the most current main branch.

This isn't quite the case: Specimin is expecting that _Specimin itself_ is correctly formatted: the target class on which Spotless is failing is `UnsolvedSymbolVisitor.java`, which is one of Specimin's internal components. 

There are at least two things wrong with this:
* _running_ Specimin should not trigger a run of Specimin's internal auto-formatter.
* even if for some reason the auto-formatter were to run, it shouldn't fail.

The error message gives a clue about the second issue: 
```
java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.JCTree com.sun.tools.javac.tree.JCTree$JCImport.getQualifiedIdentifier()'
```

This looks to me like a Java version problem; the error message led me to https://github.com/diffplug/spotless/issues/1819, which says that Spotless is using a method that was removed in Java 21. That issue is now closed, so we might be able to fix problem 2 by updating the version of the Spotless plugin that we're using. Alternatively, you could work around the problem in the short term by running with an older version of Java.

**Comment by kelloggm** [comment]
Fixed by #115.
