### ISSUE TITLE
java.nio.file.NoSuchFileException

### ISSUE THREAD

**Issue by jonathan-m-phillips** [kelloggm/specimin#153]
The following exception thrown drying running ASHE Automation.

`--args=--outputDirectory "/temp/dir" --root "root/to/randoop/agent/replacecall/src/main/java" --targetFile "randoop/instrument/MethodSignature.java" --targetMethod "randoop.instrument.MethodSignature#toString()"`

```
Exception in thread "main" java.nio.file.NoSuchFileException: /mu/absolute/path/to/randoop/agent/replacecall/src/main/java/org/plumelib/util/StringsPlume.java
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:159)
	at com.github.javaparser.Providers.provider(Providers.java:75)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:232)
	at com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:167)
	at org.checkerframework.specimin.SpeciminRunner.parseJavaFile(SpeciminRunner.java:351)
	at org.checkerframework.specimin.SpeciminRunner.performMinimization(SpeciminRunner.java:152)
	at org.checkerframework.specimin.SpeciminRunner.main(SpeciminRunner.java:64)
```

**Comment by kelloggm** [comment]
This is expected behavior.
