### ISSUE TITLE
UnsolvedSymbolException{context='CollectionsPlume.mapList...

### ISSUE THREAD

**Issue by jonathan-m-phillips** [kelloggm/specimin#154]
Found dry running ASHE Automation.

This may be associated with #151.

`--args=--outputDirectory "temp/dir" --root "root/to/randoop/agent/replacecall/src/main/java" --targetFile "randoop/instrument/ReplaceCallAgent.java" --targetMethod "randoop.instrument.ReplaceCallAgent#premain(String, Instrumentation)"`

```
Exception in thread "main" UnsolvedSymbolException{context='CollectionsPlume.mapList(MethodSignature::toString, replacementMap.keySet())', name='CollectionsPlume', cause='UnsolvedSymbolException{context='CollectionsPlume', name='Solving CollectionsPlume', cause='null'}'}
    at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:222)
    at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:166)
    at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:324)
    at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:186)
    at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:161)
    at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:315)
    at org.checkerframework.specimin.TargetMethodFinderVisitor.visit(TargetMethodFinderVisitor.java:364)
    at org.checkerframework.specimin.TargetMethodFinderVisitor.visit(TargetMethodFinderVisitor.java:47)
    at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
    at com.github.javaparser.ast.visitor.ModifierVisitor.lambda$visit$99(ModifierVisitor.java:1036)
    at java.base/java.util.Optional.map(Optional.java:260)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1036)
    at org.checkerframework.specimin.TargetMethodFinderVisitor.visit(TargetMethodFinderVisitor.java:239)
    at org.checkerframework.specimin.TargetMethodFinderVisitor.visit(TargetMethodFinderVisitor.java:47)
    at com.github.javaparser.ast.body.VariableDeclarator.accept(VariableDeclarator.java:143)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
    at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1023)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.expr.VariableDeclarationExpr.accept(VariableDeclarationExpr.java:112)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:477)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:71)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
    at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:169)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:70)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:950)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.stmt.TryStmt.accept(TryStmt.java:135)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
    at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:169)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:70)
    at com.github.javaparser.ast.visitor.ModifierVisitor.lambda$visit$60(ModifierVisitor.java:670)
    at java.base/java.util.Optional.map(Optional.java:260)
    at com.github.jav
...
```

**Comment by kelloggm** [comment]
Bug is reproducible still.

**Comment by kelloggm** [comment]
Should have been closed when #290 was merged.
