### ISSUE TITLE
jdk-8269121 minimization fails. 

### ISSUE THREAD

**Issue by tahiat** [kelloggm/specimin#233]
https://github.com/tahiat/specimin-evaluation/pull/35 contains the target projects. 

command: .`/gradlew run --args='--outputDirectory "../ISSUES/jdk-8269121/output/" --root "../ISSUES/jdk-8269121/input/TypeInferenceBugOfMethodReferences/src/main/java/" --targetFile "net/mirwaldt/bug/Main.java" --targetMethod "net.mirwaldt.bug.Main#main(String[])"'`
Exception stack:
```
Exception in thread "main" java.lang.UnsupportedOperationException: Constructor calls not yet resolvable
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodReferenceExprContext.solveMethod(MethodReferenceExprContext.java:69)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:337)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:190)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:191)
	at com.github.javaparser.ast.expr.MethodReferenceExpr.resolve(MethodReferenceExpr.java:236)
	at org.checkerframework.specimin.TargetMethodFinderVisitor.visit(TargetMethodFinderVisitor.java:421)
	at org.checkerframework.specimin.TargetMethodFinderVisitor.visit(TargetMethodFinderVisitor.java:50)
	at com.github.javaparser.ast.expr.MethodReferenceExpr.accept(MethodReferenceExpr.java:91)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
	at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
	at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:651)
```

**Comment by tahiat** [comment]
Please ignore this one as it is a runtime bug.
openjdk issue link https://bugs.openjdk.org/browse/JDK-8269121

**Comment by kelloggm** [comment]
We may want to look into this later, but closing for now since we're not interested in this target for the moment.
