### ISSUE TITLE
Troubles when running SPECIMIN with specific arguments

### ISSUE THREAD

**Issue by jonathan-m-phillips** [kelloggm/specimin#26]
I have tried to run SPICIMIN in two different ways:
1) with a wrapper in a separate program accepting the arguments through the command line
2) in SPECIMIN, as intended on the README

The command I used:
./gradlew run --args='--outputDirectory "/path/to/outputDir/src/main/java/outputDir" --root "/path/to/root/src/main/java" --targetFile "/path/njit/SocketClient.java" --targetMethod "path.njit.SocketClient#testSocket()"

I have also tried:
./gradlew run --args='--outputDirectory "/path/to/outputDir/src/main/java/outputDir" --root "/path/to/root/src/main/java" --targetFile "path/njit/SocketClient.java" --targetMethod "path.njit.SocketClient#testSocket()"

outputDirectory:
/path/to/outputDir/src/main/java/outputDir

root:
/path/to/root/src/main/java

targetFile:
/path/njit/SocketClient.java

targetMethod:
path.njit.SocketClient#testSocket() within SocketClient.java that does not take any arguments

I am running into the same exception each time. The exception mainly seems to be and issue with Symbol Solver and Java Parser.
Exception:
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to find the declaration of type ResolvedParameterDeclaration from Parameter
    at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:276)
    at com.github.javaparser.ast.body.Parameter.resolve(Parameter.java:319)
    at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:380)
    at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:55)
    at com.github.javaparser.ast.body.Parameter.accept(Parameter.java:113)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:208)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.stmt.CatchClause.accept(CatchClause.java:77)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
    at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:947)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.stmt.TryStmt.accept(TryStmt.java:135)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
    at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:169)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:70)
    at com.github.javaparser.ast.visitor.ModifierVisitor.lambda$visit$60(ModifierVisitor.java:670)
    at java.base/java.util.Optional.map(Optional.java:260)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:670)
    at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:339)
    at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:55)
    at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:98)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
    at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:243)
    at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:257)
    at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:55)
    at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:92)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
    at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:306)
    at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
    at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:127)
    at org.checkerframework.specimin.SpeciminRunner.performMinimization(SpeciminRunner.java:117)
    at org.checkerframework.specimin.SpeciminRunner.main(SpeciminRunner.java:63)

Am I doing anything wrong when passing in those arguments? From my perspective, they seem to be similar to what the README calls for.

**Comment by kelloggm** [comment]
@jonathan-m-phillips the two command strings you give appear identical. Copy-paste error?

**Comment by jonathan-m-phillips** [comment]
@kelloggm I should have been more specific. There is a slight change, where I add a forward slash in front of the targetFile, then removed it.
"/path/njit/SocketClient.java"
"path/njit/SocketClient.java"

Added an edit to the original post.

**Comment by LoiNguyenCS** [comment]
Hello @jonathan-m-phillips, can you send me the source codes of your project? I suspect that your problem has something to do with the paths that are passed to Specimin. But I am not quite sure.

**Comment by LoiNguyenCS** [comment]
This is a bug of Specimin. I've faced this issue in the past and had added a line of code to fix it. However, I forgot to note down how that line of code addressed the bug, and later, I mistakenly removed it, thinking it wasn't necessary :) Thanks for pointing it out!

**Comment by jonathan-m-phillips** [comment]
Thank you for addressing this issue. Please let me know when it is in main.
