### ISSUE TITLE
Specimin cannot handle projects that contain a wildcard import

### ISSUE THREAD

**Issue by tahiat** [kelloggm/specimin#62]
SPECIMIN execution to minimize cf-6030 issue gives following exception 

**Command**: 
`./gradlew run --args='--outputDirectory "../ISSUES/CF/cf-6030/output/" --root "../ISSUES/CF/cf-6030/input/cassandra/src/java/" --targetFile "org/apache/cassandra/service/reads/DataResolver.java" --targetMethod "org.apache.cassandra.service.reads.DataResolver#getData()"'`

**Exception traces**: 

```
Exception in thread "main" java.lang.IllegalStateException:  is not ClassOrInterfaceType, it is UnknownType
        at com.github.javaparser.ast.type.Type.asClassOrInterfaceType(Type.java:176)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.handleParameterResolveFailure(UnsolvedSymbolVisitor.java:724)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:678)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:73)
        at com.github.javaparser.ast.body.Parameter.accept(Parameter.java:113)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1087)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.expr.LambdaExpr.accept(LambdaExpr.java:162)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:651)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:580)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:73)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1001)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.expr.UnaryExpr.accept(UnaryExpr.java:112)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:128)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.stmt.AssertStmt.accept(AssertStmt.java:79)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:169)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:407)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:73)
        at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:70)
        at com.github.javaparser.ast.visitor.ModifierVisitor.lambda$visit$60(ModifierVisitor.java:670)
        at java.base/java.util.Optional.map(Optional.java:265)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:670)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:554)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:73)
        at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:98)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:243)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:286)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:73)
        at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:92)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:306)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:127)
        at org.checkerframework.specimin.SpeciminRunner.performMinimization(SpeciminRunner.java:123)
        at org.checkerframework.specimin.SpeciminRunner.main(SpeciminRunner.java:63)

FAILURE: Build failed with an exception.
```

The project file is uploaded in the [drive](https://drive.google.com/file/d/14x-4gqDEZHA6nyXfkosbkSoQRPDVpJsc/view?usp=drive_link) and accessible with njit

**Comment by tahiat** [comment]
cf-4614 also face this issue. Project [link](https://drive.google.com/drive/folders/1iCyPOTrIgskaAjXdXlUGreGlLU10ys82?usp=drive_link)

**Comment by tahiat** [comment]
minimized test case: 
```
class Simple {

    public void test() {
        List<FullName> names = new ArrayList<>();
        names.add(new FullName("A", "b"));
        names.add(new FullName("C", "D"));

        names.forEach(name -> { // -->.    name parameter causing crash.
            System.out.println(name.getFirstName());
            System.out.println(name.getLastName());
        });
    }
}
```

**Comment by LoiNguyenCS** [comment]
I don't think we can solve this issue. The original file has a wildcard import. Specimin won't work with wildcard import statements.

**Comment by kelloggm** [comment]
> Specimin won't work with wildcard import statements

While that's true, we should still do better than crashing in that case. Ideally, we'd report a helpful error to the user that indicates that Specimin cannot be used with wildcard imports rather than crashing.

**Comment by LoiNguyenCS** [comment]
> While that's true, we should still do better than crashing in that case. Ideally, we'd report a helpful error to the user that indicates that Specimin cannot be used with wildcard imports rather than crashing.


I've added a condition check so that Specimin will return a help error message before crashing in this PR #66.
