### ISSUE TITLE
specimin execution fails for cf-6282

### ISSUE THREAD

**Issue by tahiat** [kelloggm/specimin#64]
command: 
`./gradlew run --args='--outputDirectory "../ISSUES/CF/cf-6282/output/" --root "../ISSUES/CF/cf-6282/input/Chronicle-Core/src/main/java/" --targetFile "net/openhft/chronicle/core/internal/ClassUtil.java" --targetMethod "net.openhft.chronicle.core.internal.ClassUtil#setAccessible(AccessibleObject)"'`

stack tracke: 

```
build error: 
> Task :run FAILED
Exception in thread "main" UnsolvedSymbolException{context='null', name='AccessibleObject', cause='null'}
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:682)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:740)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:736)
        at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserParameterDeclaration.getType(JavaParserParameterDeclaration.java:69)
        at com.github.javaparser.resolution.declarations.ResolvedParameterDeclaration.describeType(ResolvedParameterDeclaration.java:61)
        at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getSignature(ResolvedMethodLikeDeclaration.java:71)
        at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getQualifiedSignature(ResolvedMethodLikeDeclaration.java:82)
        at org.checkerframework.specimin.PrunerVisitor.visit(PrunerVisitor.java:95)
        at org.checkerframework.specimin.PrunerVisitor.visit(PrunerVisitor.java:32)
        at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:98)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:243)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:92)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:306)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:127)
        at org.checkerframework.specimin.SpeciminRunner.performMinimization(SpeciminRunner.java:193)
        at org.checkerframework.specimin.SpeciminRunner.main(SpeciminRunner.java:63)

FAILURE: Build failed with an exception.
```

Project files is [here](https://drive.google.com/file/d/1nllM6munToyAnPTG60f-8AAbzXvSRKhS/view?usp=sharing).

**Comment by LoiNguyenCS** [comment]
This issue also has a wildcard import in its target file.

**Comment by kelloggm** [comment]
Closing as duplicate of #62
