### ISSUE TITLE
minimization fails for cf-3850 issue

### ISSUE THREAD

**Issue by tahiat** [kelloggm/specimin#65]
cf issue link: [cf-3850](https://github.com/typetools/checker-framework/issues/3850)

command: 
`./gradlew run --args='--outputDirectory "../ISSUES/CF/cf-3850/output/" --root "../ISSUES/CF/cf-3850/input/calcite/core/src/main/java/" --targetFile "org/apache/calcite/sql/parser/SqlParserPos.java" --targetMethod "org.apache.calcite.sql.parser.SqlParserPos#toPos(Iterable<? extends @PolyNull SqlNode>)"'`

strace:
```
> Task :run FAILED
Exception in thread "main" java.lang.RuntimeException: Unexpected expression: LambdaConstraintType{bound=TypeVariable {JPTypeParameter(T, bounds=[])}}
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.getSyntheticClass(UnsolvedSymbolVisitor.java:1297)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:616)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:73)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:319)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.expr.ConditionalExpr.accept(ConditionalExpr.java:76)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:477)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:71)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1086)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.expr.LambdaExpr.accept(LambdaExpr.java:162)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:651)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:610)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:73)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.ast.visitor.ModifierVisitor.lambda$visit$79(ModifierVisitor.java:852)
        at java.base/java.util.Optional.map(Optional.java:265)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:852)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.stmt.ReturnStmt.accept(ReturnStmt.java:78)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:169)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:413)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:73)
        at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:70)
        at com.github.javaparser.ast.visitor.ModifierVisitor.lambda$visit$60(ModifierVisitor.java:670)
        at java.base/java.util.Optional.map(Optional.java:265)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:670)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:560)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:73)
        at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:98)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:243)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:292)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:73)
        at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:92)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:306)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
        at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:127)
        at org.checkerframework.specimin.SpeciminRunner.performMinimization(SpeciminRunner.java:123)
        at org.checkerframework.specimin.SpeciminRunner.main(SpeciminRunner.java:63)

FAILURE: Build failed with an exception.
```

project [file](https://drive.google.com/file/d/1oXQ83gMzI02ggSxaKgz1kUj0y7uRFuiU/view?usp=sharing)

**Comment by LoiNguyenCS** [comment]
The bug in this issue has to do with **unknown type**, such as `List<?>`. If the unknown type is an extension of some other types, such as `void test(Iterable<? extends Calculator> node)`, then the behavior of JavaParser is quite unpredictable, even if the class `Calculator` is resolved. For example, if the class `Calculator` is resolved, then we can resolve parameter `node` and method `test`, but we will get an UnsolvedSymbolException if we do `test.resolve().getQualifiedSignature()`. In some other cases, we can't even resolve the parameter if it has an unknown type. I have not fully understood why there are such different behaviors.

**Comment by kelloggm** [comment]
> The bug in this issue has to do with unknown type, such as `List<?>`

This is called a wildcard type, and we definitely need to support them. However, I'm not surprised that some JavaParser APIs don't work quite right in the presence of these. Let's add a few tests that use them and then make sure that we at least fail in a sensible way in these cases.

**Comment by kelloggm** [comment]
>  I am afraid that if we skip every codebase that use wildcard types, we might not have enough experiment data for our paper

I agree that we cannot skip every codebase that uses wildcards. Would it be possible to only fail if the **target method** uses wildcards, rather than the codebase? That might be ok.

>  I can try writing an alternative version of `getQualifiedSignature()`

Long-term, this is the right solution: we need to handle this kind of code if we want Specimin to be useful for debugging analysis tool crashes, which often do involve wildcards in practice - they're also hard for analysis developers!

**Comment by LoiNguyenCS** [comment]
> Would it be possible to only fail if the target method uses wildcards, rather than the codebase? That might be ok.

I think this is rather difficult. Because we need `getQualifiedSignature()` to know if a method is used by the target method or not. So if a method has wildcards, we will not be able to determine if that method should be emptied or removed, since we can't extract its signature for comparison.
