### ISSUE TITLE
Crash in FieldDeclarationVisitor for field declaration inside anonymous class : cf-689

### ISSUE THREAD

**Issue by tahiat** [kelloggm/specimin#73]
SPECIMIN crashes when casting `FieldDeclaration` inside anonymous class to `ClassOrInterfaceDeclaration`

Command: `./gradlew run --args='--outputDirectory "../ISSUES/CF/cf-689/output/" --root "../ISSUES/CF/cf-689/input/Issue689/" --targetFile "java/util/AbstractList.java" --targetMethod "java.util.SubList#listIterator(SubList<E>, int)"'`

Exception: 
```
Exception in thread "main" java.lang.ClassCastException: class com.github.javaparser.ast.expr.ObjectCreationExpr cannot be cast to class com.github.javaparser.ast.body.ClassOrInterfaceDeclaration (com.github.javaparser.ast.expr.ObjectCreationExpr and com.github.javaparser.ast.body.ClassOrInterfaceDeclaration are in unnamed module of loader 'app')
        at org.checkerframework.specimin.FieldDeclarationsVisitor.visit(FieldDeclarationsVisitor.java:35)
        at org.checkerframework.specimin.FieldDeclarationsVisitor.visit(FieldDeclarationsVisitor.java:19)
        at com.github.javaparser.ast.body.FieldDeclaration.accept(FieldDeclaration.java:116)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$117(VoidVisitorAdapter.java:402)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at com.github.javaparser.ast.NodeList.forEach(NodeList.java:290)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$118(VoidVisitorAdapter.java:402)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:402)
        at com.github.javaparser.ast.expr.ObjectCreationExpr.accept(ObjectCreationExpr.java:118)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$146(VoidVisitorAdapter.java:474)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:474)
        at com.github.javaparser.ast.stmt.ReturnStmt.accept(ReturnStmt.java:84)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$19(VoidVisitorAdapter.java:109)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at com.github.javaparser.ast.NodeList.forEach(NodeList.java:290)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:109)
        at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:76)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$105(VoidVisitorAdapter.java:370)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:370)
        at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:104)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$31(VoidVisitorAdapter.java:154)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at com.github.javaparser.ast.NodeList.forEach(NodeList.java:290)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:154)
        at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:98)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$43(VoidVisitorAdapter.java:175)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at com.github.javaparser.ast.NodeList.forEach(NodeList.java:290)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:175)
        at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:133)
        at org.checkerframework.specimin.SpeciminRunner.performMinimization(SpeciminRunner.java:129)
        at org.checkerframework.specimin.SpeciminRunner.main(SpeciminRunner.java:64)
```

Specimin [input](https://drive.google.com/file/d/1Uw9a_wntcQykbC36NIyToNoRJOaVHANo/view?usp=drive_link)

**Comment by LoiNguyenCS** [comment]
To recognize anonymous classes, `UnsolvedSymbolVisitor` has a field called `insideAnObjectCreation` to check if the currently visiting element is inside an object creation expression.

This field is set to true whenever we enter an `ObjectCreationExpr` and false whenever we get out of an `ObjectCreationExpr`. So if there is an `ObjectCreationExpr` inside an `ObjectCreationExpr`, our check fails.

**Comment by kelloggm** [comment]
> To recognize anonymous classes, `UnsolvedSymbolVisitor` has a field called `insideAnObjectCreation` to check if the currently visiting element is inside an object creation expression.
> 
> This field is set to true whenever we enter an `ObjectCreationExpr` and false whenever we get out of an `ObjectCreationExpr`. So if there is an `ObjectCreationExpr` inside an `ObjectCreationExpr`, our check fails.

The solution to this problem is almost certainly to keep more information than just a boolean: an integer for the number of object creations deep that we are should do it (the current field's behavior can be modeled as "true when 0; false otherwise"; we can write a helper method that encodes this and replace all uses of the current field by that helper).
